###############################
#  Taps                       #
###############################
tap "oven-sh/bun" # for bun

###############################
#  Brews                      #
###############################

# Binaries
brew "bat" # better cat
brew "fzf" # fuzzy finding
brew "fd" # better find
brew "ripgrep" # better grep
brew "eza" # better ls
brew "zoxide" # better cd
brew "the_silver_searcher" # better ack
brew "git" # Git
brew "gh" # GitHub CLI
brew "node" # Node
brew "oven-sh/bun/bun" # Bun
brew "hyperfine" # Benchmarking tool
brew "jump" # Utility tool to jump to directories
brew "fish" # Shell
brew "fisher" # Package manager for Fish shell
# brew "tmux" # Terminal Multiplexer (optional, using ghostty)
# brew "httpie" # HTTP CLI Client
brew "duf" # Disk Usage Utility - 'df' alternative
brew "git-delta" # Better diff tool
brew "neovim" # Neovim
brew "lazygit" # Best Git Client
brew "opencode" # AI Coding TUI
brew "uv" # Python Pip alternative

# Other
brew "mas" # to install app store apps

###############################
#  Casks                      #
###############################

# Utilities
cask "clop" # Clipboard auto-optimizer
cask "alt-tab" # Command-Tab alternative that iterates over windows (and excludes finder)

# Browsers
cask "arc" # Opinionated browser I like

# Productivity
cask "amie" # Calendar and Task manager (take it from my cold dead hands)

# Password manager
cask "1password" # Password manager of choice
cask "1password-cli" # CLI support for password manager

# Social
cask "discord"
cask "whatsapp"

# Development
cask "cursor" # AI IDE of choice
cask "ghostty" # Best Terminal, doesn't have a session manager yet
cask "orbstack" # Docker Desktop alternative with excellent Mac support

# Fonts
cask "font-jetbrains-mono-nerd-font" # Best font with NeoVim in my experience

###############################
#  macOS Apps via App Store   #
###############################

# Utilities
mas "Dropover", id: 1355679052 # Save files in shelves by dragging to the corner
mas "Magnet", id: 441258766 # Window snapping tool
mas "Pure Paste", id: 1611378436 # Remove formatting and keeps only the text from clipboard
mas "rcmd", id: 1596283165 # Keybindings-focused window switcher
mas "Klack", id: 6446206067 # Funny mechanical keyboard sounds
mas "Flighty", id: 1358823008 # Best flight tracker
mas "Command X", id: 6448461551 # Cut and paste support for Finder

###############################
# Interesting apps and ideas  #
###############################

# cask "Raycast" # Better spotlight, Tahoe spotlight is good enough for me
# mas "Alcove" # Interesting use case for notch, Tahoe changed volume and brightness
