###############################
#  Taps                       #
###############################
tap "homebrew/bundle" # for brew bundle
tap "oven-sh/bun" # for bun

###############################
#  Brews                      #
###############################

# Binaries
brew "bat" # better cat
brew "fd" # better find
brew "ripgrep" # better grep
brew "eza" # better ls
brew "zoxide" # better cd
brew "the_silver_searcher" # better ack
brew "git" # Git
brew "gh" # GitHub CLI
brew "node" # Node
brew 'rust' # Rust
brew "oven-sh/bun/bun" # Bun
brew "hyperfine" # Benchmarking tool
brew "jump" # Utility tool to jump to directories
brew "fish" # Shell
# brew "tmux" # Terminal Multiplexer (optional, using wezterm)
brew "httpie" # HTTP CLI Client
brew "duf" # Disk Usage Utility - 'df' alternative
brew "git-delta" # Better diff tool
brew "neovim" # Neovim
brew "lazygit" # Best Git Client

# Other
brew "mas" # to install app store apps

###############################
#  Casks                      #
###############################

# Utilities
cask "clop" # Clipboard auto-optimizer
cask "command-x" # Cut and paste support for Finder

# Browsers
cask "arc" # Opinionated browser I like

# Password manager
cask "1password" # Password manager of choice
cask "1password-cli" # CLI support for password manager

# Social
cask "discord"
cask "whatsapp"

# Development
cask "cursor" # Cursor IDE
cask "wezterm@nightly" # GPU-accelerated and Lua-scriptable fast terminal emulator
cask "ghostty" # Best Terminal, doesn't have my Lua sessionizer yet, alternating
cask "orbstack" # Docker Desktop alternative with excellent Mac support

# Fonts
cask "font-jetbrains-mono-nerd-font" # Best font with NeoVim in my experience

###############################
#  macOS Apps via App Store   #
###############################

# Utilities
mas "Dropover", id: 1355679052 # Save files in shelves by dragging to the corner
mas "Magnet", id: 441258766 # Window snapping tool
mas "Pure Paste", id: 1611378436 # Remove formatting and keeps only the text from clipboard
mas "rcmd", id: 1596283165 # Keybindings-focused window switcher

###############################
# Interesting apps and ideas  #
###############################

# mas "Klack" # Funny mechanical keyboard sounds
# cask "Raycast" # Better spotlight, Tahoe spotlight is good enough for me
# brew "lazydocker" # Docker TUI, I don't use docker enough for it
# mas "Alcove" # Interesting use case for notch, Tahoe changed volume and brightness
# cask "rapidapi" # API devtools, Postman replacement
