#!/bin/bash

# Generated by dotbash
set -e

echo "Setting up: ~/.gitconfig -> git/.gitconfig"
if [ ! -e "$(pwd)/git/.gitconfig" ]; then
  echo "  ✗ Error: Source does not exist: git/.gitconfig"
  exit 1
fi
mkdir -p "$(dirname "$HOME/.gitconfig")"
if [ -e "$HOME/.gitconfig" ] || [ -L "$HOME/.gitconfig" ]; then
  echo "  Removing existing: ~/.gitconfig"
  rm -rf "$HOME/.gitconfig"
fi
ln -s "$(pwd)/git/.gitconfig" "$HOME/.gitconfig"
echo "  ✓ Linked ~/.gitconfig"

echo "Setting up: ~/.gitignore_global -> git/.gitignore_global"
if [ ! -e "$(pwd)/git/.gitignore_global" ]; then
  echo "  ✗ Error: Source does not exist: git/.gitignore_global"
  exit 1
fi
mkdir -p "$(dirname "$HOME/.gitignore_global")"
if [ -e "$HOME/.gitignore_global" ] || [ -L "$HOME/.gitignore_global" ]; then
  echo "  Removing existing: ~/.gitignore_global"
  rm -rf "$HOME/.gitignore_global"
fi
ln -s "$(pwd)/git/.gitignore_global" "$HOME/.gitignore_global"
echo "  ✓ Linked ~/.gitignore_global"

echo "Setting up: ~/.config/git/delta/tokyonight_night.gitconfig -> git/extra/delta/tokyonight_night.gitconfig"
if [ ! -e "$(pwd)/git/extra/delta/tokyonight_night.gitconfig" ]; then
  echo "  ✗ Error: Source does not exist: git/extra/delta/tokyonight_night.gitconfig"
  exit 1
fi
mkdir -p "$(dirname "$HOME/.config/git/delta/tokyonight_night.gitconfig")"
if [ -e "$HOME/.config/git/delta/tokyonight_night.gitconfig" ] || [ -L "$HOME/.config/git/delta/tokyonight_night.gitconfig" ]; then
  echo "  Removing existing: ~/.config/git/delta/tokyonight_night.gitconfig"
  rm -rf "$HOME/.config/git/delta/tokyonight_night.gitconfig"
fi
ln -s "$(pwd)/git/extra/delta/tokyonight_night.gitconfig" "$HOME/.config/git/delta/tokyonight_night.gitconfig"
echo "  ✓ Linked ~/.config/git/delta/tokyonight_night.gitconfig"

echo "Setting up: ~/.config/nvim -> nvim"
if [ ! -e "$(pwd)/nvim" ]; then
  echo "  ✗ Error: Source does not exist: nvim"
  exit 1
fi
mkdir -p "$(dirname "$HOME/.config/nvim")"
if [ -e "$HOME/.config/nvim" ] || [ -L "$HOME/.config/nvim" ]; then
  echo "  Removing existing: ~/.config/nvim"
  rm -rf "$HOME/.config/nvim"
fi
ln -s "$(pwd)/nvim" "$HOME/.config/nvim"
echo "  ✓ Linked ~/.config/nvim"

echo "Setting up: ~/.config/fish -> fish"
if [ ! -e "$(pwd)/fish" ]; then
  echo "  ✗ Error: Source does not exist: fish"
  exit 1
fi
mkdir -p "$(dirname "$HOME/.config/fish")"
if [ -e "$HOME/.config/fish" ] || [ -L "$HOME/.config/fish" ]; then
  echo "  Removing existing: ~/.config/fish"
  rm -rf "$HOME/.config/fish"
fi
ln -s "$(pwd)/fish" "$HOME/.config/fish"
echo "  ✓ Linked ~/.config/fish"

echo "Setting up: ~/.config/bat -> bat"
if [ ! -e "$(pwd)/bat" ]; then
  echo "  ✗ Error: Source does not exist: bat"
  exit 1
fi
mkdir -p "$(dirname "$HOME/.config/bat")"
if [ -e "$HOME/.config/bat" ] || [ -L "$HOME/.config/bat" ]; then
  echo "  Removing existing: ~/.config/bat"
  rm -rf "$HOME/.config/bat"
fi
ln -s "$(pwd)/bat" "$HOME/.config/bat"
echo "  ✓ Linked ~/.config/bat"

echo "Setting up: ~/.config/ghostty -> ghostty"
if [ ! -e "$(pwd)/ghostty" ]; then
  echo "  ✗ Error: Source does not exist: ghostty"
  exit 1
fi
mkdir -p "$(dirname "$HOME/.config/ghostty")"
if [ -e "$HOME/.config/ghostty" ] || [ -L "$HOME/.config/ghostty" ]; then
  echo "  Removing existing: ~/.config/ghostty"
  rm -rf "$HOME/.config/ghostty"
fi
ln -s "$(pwd)/ghostty" "$HOME/.config/ghostty"
echo "  ✓ Linked ~/.config/ghostty"

echo "Setting up: ~/.config/opencode -> opencode"
if [ ! -e "$(pwd)/opencode" ]; then
  echo "  ✗ Error: Source does not exist: opencode"
  exit 1
fi
mkdir -p "$(dirname "$HOME/.config/opencode")"
if [ -e "$HOME/.config/opencode" ] || [ -L "$HOME/.config/opencode" ]; then
  echo "  Removing existing: ~/.config/opencode"
  rm -rf "$HOME/.config/opencode"
fi
ln -s "$(pwd)/opencode" "$HOME/.config/opencode"
echo "  ✓ Linked ~/.config/opencode"

echo "Setting up: ~/.config/lazygit/config.yml -> lazygit/config.yml"
if [ ! -e "$(pwd)/lazygit/config.yml" ]; then
  echo "  ✗ Error: Source does not exist: lazygit/config.yml"
  exit 1
fi
mkdir -p "$(dirname "$HOME/.config/lazygit/config.yml")"
if [ -e "$HOME/.config/lazygit/config.yml" ] || [ -L "$HOME/.config/lazygit/config.yml" ]; then
  echo "  Removing existing: ~/.config/lazygit/config.yml"
  rm -rf "$HOME/.config/lazygit/config.yml"
fi
ln -s "$(pwd)/lazygit/config.yml" "$HOME/.config/lazygit/config.yml"
echo "  ✓ Linked ~/.config/lazygit/config.yml"

echo "All symlinks created successfully!"

# Package Manager Setup
if [[ "$(uname)" == "Darwin" ]]; then
  # Install Homebrew
  echo "Checking for Homebrew..."
  if command -v brew &>/dev/null; then
    echo "  ✓ Homebrew already installed"
  else
    echo "  Installing Homebrew..."
    if /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"; then
      echo "  ✓ Homebrew installed successfully"
    else
      echo "  ✗ Error: Failed to install Homebrew"
      exit 1
    fi
  fi

  # Install packages from Brewfile
  if [ ! -e "$(pwd)/brew/Brewfile" ]; then
    echo "  ✗ Error: Brewfile not found: brew/Brewfile"
    exit 1
  fi
  echo "Installing packages from brew/Brewfile..."
  if brew bundle --file="$(pwd)/brew/Brewfile"; then
    echo "  ✓ Packages installed successfully"
  else
    echo "  ✗ Error: Failed to install packages"
    exit 1
  fi
fi

# Set Fish as default shell
echo "Set Fish as default shell..."
if (FP=$(command -v fish)
grep -Fxq "$FP" /etc/shells || echo "$FP" | sudo tee -a /etc/shells
[ "$SHELL" = "$FP" ] || chsh -s "$FP" "$USER"
); then
  echo "  ✓ Set Fish as default shell completed"
else
  echo "  ✗ Error: Set Fish as default shell failed"
  exit 1
fi

# Install Fish Plugins
echo "Install Fish Plugins..."
if (fish -c "fisher update"); then
  echo "  ✓ Install Fish Plugins completed"
else
  echo "  ✗ Error: Install Fish Plugins failed"
  exit 1
fi

# Generate Fish completions
echo "Generate Fish completions..."
if (COMPDIR="$HOME/.config/fish/completions"
mkdir -p "$COMPDIR"

emit() {
  local bin="$1" dest="$2"
  shift 2
  if command -v "$bin" >/dev/null 2>&1; then
    "$@" >"$dest" || rm -f "$dest"
  fi
}

emit docker "$COMPDIR/docker.fish" docker completion fish
emit kubectl "$COMPDIR/kubectl.fish" kubectl completion fish
emit gh "$COMPDIR/gh.fish" gh completion -s fish
emit supabase "$COMPDIR/supabase.fish" supabase completion fish
emit orbctl "$COMPDIR/orbctl.fish" orbctl completion fish

if command -v bun >/dev/null 2>&1; then
  bun completions "$COMPDIR" >/dev/null 2>&1 || true
fi
); then
  echo "  ✓ Generate Fish completions completed"
else
  echo "  ✗ Error: Generate Fish completions failed"
  exit 1
fi

echo "All shell commands completed successfully!"

