#!/bin/bash

# Generated by dotbash
set -e

DRY_RUN=false
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=true ;;
  esac
done

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

dotbash_run() {
  if [ "$DRY_RUN" = true ]; then
    echo "[dry-run] $*"
  else
    "$@"
  fi
}

dotbash_configure_brew_path() {
  if [ -x /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [ -x /usr/local/bin/brew ]; then
    eval "$(/usr/local/bin/brew shellenv)"
  fi
}

echo "Setting up: ~/.gitconfig -> git/.gitconfig"
if [ ! -e "$ROOT"/git/.gitconfig ]; then
  echo "  ✗ Error: Source does not exist: git/.gitconfig"
  exit 1
fi
if [ -L "$HOME/.gitconfig" ] && [ "$(readlink "$HOME/.gitconfig")" = "$ROOT"/git/.gitconfig ]; then
  echo "  ✓ Already linked ~/.gitconfig"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.gitconfig -> git/.gitconfig"
  else
    mkdir -p "$(dirname "$HOME/.gitconfig")"
    if [ -e "$HOME/.gitconfig" ] || [ -L "$HOME/.gitconfig" ]; then
      echo "  Removing existing: ~/.gitconfig"
      rm -rf "$HOME/.gitconfig"
    fi
    ln -s "$ROOT"/git/.gitconfig "$HOME/.gitconfig"
    echo "  ✓ Linked ~/.gitconfig"
  fi
fi

echo "Setting up: ~/.gitignore_global -> git/.gitignore_global"
if [ ! -e "$ROOT"/git/.gitignore_global ]; then
  echo "  ✗ Error: Source does not exist: git/.gitignore_global"
  exit 1
fi
if [ -L "$HOME/.gitignore_global" ] && [ "$(readlink "$HOME/.gitignore_global")" = "$ROOT"/git/.gitignore_global ]; then
  echo "  ✓ Already linked ~/.gitignore_global"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.gitignore_global -> git/.gitignore_global"
  else
    mkdir -p "$(dirname "$HOME/.gitignore_global")"
    if [ -e "$HOME/.gitignore_global" ] || [ -L "$HOME/.gitignore_global" ]; then
      echo "  Removing existing: ~/.gitignore_global"
      rm -rf "$HOME/.gitignore_global"
    fi
    ln -s "$ROOT"/git/.gitignore_global "$HOME/.gitignore_global"
    echo "  ✓ Linked ~/.gitignore_global"
  fi
fi

echo "Setting up: ~/.config/git/delta/tokyonight_night.gitconfig -> git/extra/delta/tokyonight_night.gitconfig"
if [ ! -e "$ROOT"/git/extra/delta/tokyonight_night.gitconfig ]; then
  echo "  ✗ Error: Source does not exist: git/extra/delta/tokyonight_night.gitconfig"
  exit 1
fi
if [ -L "$HOME/.config/git/delta/tokyonight_night.gitconfig" ] && [ "$(readlink "$HOME/.config/git/delta/tokyonight_night.gitconfig")" = "$ROOT"/git/extra/delta/tokyonight_night.gitconfig ]; then
  echo "  ✓ Already linked ~/.config/git/delta/tokyonight_night.gitconfig"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.config/git/delta/tokyonight_night.gitconfig -> git/extra/delta/tokyonight_night.gitconfig"
  else
    mkdir -p "$(dirname "$HOME/.config/git/delta/tokyonight_night.gitconfig")"
    if [ -e "$HOME/.config/git/delta/tokyonight_night.gitconfig" ] || [ -L "$HOME/.config/git/delta/tokyonight_night.gitconfig" ]; then
      echo "  Removing existing: ~/.config/git/delta/tokyonight_night.gitconfig"
      rm -rf "$HOME/.config/git/delta/tokyonight_night.gitconfig"
    fi
    ln -s "$ROOT"/git/extra/delta/tokyonight_night.gitconfig "$HOME/.config/git/delta/tokyonight_night.gitconfig"
    echo "  ✓ Linked ~/.config/git/delta/tokyonight_night.gitconfig"
  fi
fi

echo "Setting up: ~/.config/nvim -> nvim"
if [ ! -e "$ROOT"/nvim ]; then
  echo "  ✗ Error: Source does not exist: nvim"
  exit 1
fi
if [ -L "$HOME/.config/nvim" ] && [ "$(readlink "$HOME/.config/nvim")" = "$ROOT"/nvim ]; then
  echo "  ✓ Already linked ~/.config/nvim"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.config/nvim -> nvim"
  else
    mkdir -p "$(dirname "$HOME/.config/nvim")"
    if [ -e "$HOME/.config/nvim" ] || [ -L "$HOME/.config/nvim" ]; then
      echo "  Removing existing: ~/.config/nvim"
      rm -rf "$HOME/.config/nvim"
    fi
    ln -s "$ROOT"/nvim "$HOME/.config/nvim"
    echo "  ✓ Linked ~/.config/nvim"
  fi
fi

echo "Setting up: ~/.config/fish -> fish"
if [ ! -e "$ROOT"/fish ]; then
  echo "  ✗ Error: Source does not exist: fish"
  exit 1
fi
if [ -L "$HOME/.config/fish" ] && [ "$(readlink "$HOME/.config/fish")" = "$ROOT"/fish ]; then
  echo "  ✓ Already linked ~/.config/fish"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.config/fish -> fish"
  else
    mkdir -p "$(dirname "$HOME/.config/fish")"
    if [ -e "$HOME/.config/fish" ] || [ -L "$HOME/.config/fish" ]; then
      echo "  Removing existing: ~/.config/fish"
      rm -rf "$HOME/.config/fish"
    fi
    ln -s "$ROOT"/fish "$HOME/.config/fish"
    echo "  ✓ Linked ~/.config/fish"
  fi
fi

echo "Setting up: ~/.config/bat -> bat"
if [ ! -e "$ROOT"/bat ]; then
  echo "  ✗ Error: Source does not exist: bat"
  exit 1
fi
if [ -L "$HOME/.config/bat" ] && [ "$(readlink "$HOME/.config/bat")" = "$ROOT"/bat ]; then
  echo "  ✓ Already linked ~/.config/bat"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.config/bat -> bat"
  else
    mkdir -p "$(dirname "$HOME/.config/bat")"
    if [ -e "$HOME/.config/bat" ] || [ -L "$HOME/.config/bat" ]; then
      echo "  Removing existing: ~/.config/bat"
      rm -rf "$HOME/.config/bat"
    fi
    ln -s "$ROOT"/bat "$HOME/.config/bat"
    echo "  ✓ Linked ~/.config/bat"
  fi
fi

echo "Setting up: ~/.config/ghostty -> ghostty"
if [ ! -e "$ROOT"/ghostty ]; then
  echo "  ✗ Error: Source does not exist: ghostty"
  exit 1
fi
if [ -L "$HOME/.config/ghostty" ] && [ "$(readlink "$HOME/.config/ghostty")" = "$ROOT"/ghostty ]; then
  echo "  ✓ Already linked ~/.config/ghostty"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.config/ghostty -> ghostty"
  else
    mkdir -p "$(dirname "$HOME/.config/ghostty")"
    if [ -e "$HOME/.config/ghostty" ] || [ -L "$HOME/.config/ghostty" ]; then
      echo "  Removing existing: ~/.config/ghostty"
      rm -rf "$HOME/.config/ghostty"
    fi
    ln -s "$ROOT"/ghostty "$HOME/.config/ghostty"
    echo "  ✓ Linked ~/.config/ghostty"
  fi
fi

echo "Setting up: ~/.config/opencode -> opencode"
if [ ! -e "$ROOT"/opencode ]; then
  echo "  ✗ Error: Source does not exist: opencode"
  exit 1
fi
if [ -L "$HOME/.config/opencode" ] && [ "$(readlink "$HOME/.config/opencode")" = "$ROOT"/opencode ]; then
  echo "  ✓ Already linked ~/.config/opencode"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.config/opencode -> opencode"
  else
    mkdir -p "$(dirname "$HOME/.config/opencode")"
    if [ -e "$HOME/.config/opencode" ] || [ -L "$HOME/.config/opencode" ]; then
      echo "  Removing existing: ~/.config/opencode"
      rm -rf "$HOME/.config/opencode"
    fi
    ln -s "$ROOT"/opencode "$HOME/.config/opencode"
    echo "  ✓ Linked ~/.config/opencode"
  fi
fi

echo "Setting up: ~/.config/lazygit/config.yml -> lazygit/config.yml"
if [ ! -e "$ROOT"/lazygit/config.yml ]; then
  echo "  ✗ Error: Source does not exist: lazygit/config.yml"
  exit 1
fi
if [ -L "$HOME/.config/lazygit/config.yml" ] && [ "$(readlink "$HOME/.config/lazygit/config.yml")" = "$ROOT"/lazygit/config.yml ]; then
  echo "  ✓ Already linked ~/.config/lazygit/config.yml"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.config/lazygit/config.yml -> lazygit/config.yml"
  else
    mkdir -p "$(dirname "$HOME/.config/lazygit/config.yml")"
    if [ -e "$HOME/.config/lazygit/config.yml" ] || [ -L "$HOME/.config/lazygit/config.yml" ]; then
      echo "  Removing existing: ~/.config/lazygit/config.yml"
      rm -rf "$HOME/.config/lazygit/config.yml"
    fi
    ln -s "$ROOT"/lazygit/config.yml "$HOME/.config/lazygit/config.yml"
    echo "  ✓ Linked ~/.config/lazygit/config.yml"
  fi
fi

echo "Setting up: ~/.mackup.cfg -> mackup/mackup.cfg"
if [ ! -e "$ROOT"/mackup/mackup.cfg ]; then
  echo "  ✗ Error: Source does not exist: mackup/mackup.cfg"
  exit 1
fi
if [ -L "$HOME/.mackup.cfg" ] && [ "$(readlink "$HOME/.mackup.cfg")" = "$ROOT"/mackup/mackup.cfg ]; then
  echo "  ✓ Already linked ~/.mackup.cfg"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.mackup.cfg -> mackup/mackup.cfg"
  else
    mkdir -p "$(dirname "$HOME/.mackup.cfg")"
    if [ -e "$HOME/.mackup.cfg" ] || [ -L "$HOME/.mackup.cfg" ]; then
      echo "  Removing existing: ~/.mackup.cfg"
      rm -rf "$HOME/.mackup.cfg"
    fi
    ln -s "$ROOT"/mackup/mackup.cfg "$HOME/.mackup.cfg"
    echo "  ✓ Linked ~/.mackup.cfg"
  fi
fi

echo "Setting up: ~/.mackup -> mackup/applications"
if [ ! -e "$ROOT"/mackup/applications ]; then
  echo "  ✗ Error: Source does not exist: mackup/applications"
  exit 1
fi
if [ -L "$HOME/.mackup" ] && [ "$(readlink "$HOME/.mackup")" = "$ROOT"/mackup/applications ]; then
  echo "  ✓ Already linked ~/.mackup"
else
  if [ "$DRY_RUN" = true ]; then
    echo "  [dry-run] would link ~/.mackup -> mackup/applications"
  else
    mkdir -p "$(dirname "$HOME/.mackup")"
    if [ -e "$HOME/.mackup" ] || [ -L "$HOME/.mackup" ]; then
      echo "  Removing existing: ~/.mackup"
      rm -rf "$HOME/.mackup"
    fi
    ln -s "$ROOT"/mackup/applications "$HOME/.mackup"
    echo "  ✓ Linked ~/.mackup"
  fi
fi

echo "All symlinks created successfully!"

# Package Manager Setup
if [[ "$(uname)" == "Darwin" ]]; then
  echo "Checking for Homebrew..."
  if command -v brew &>/dev/null; then
    echo "  ✓ Homebrew already installed"
  else
    echo "  Installing Homebrew..."
    if [ "$DRY_RUN" = true ]; then
      echo "[dry-run] install Homebrew"
    else
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      echo "  ✓ Homebrew installed successfully"
    fi
  fi
  dotbash_configure_brew_path

  if [ ! -e "$ROOT"/brew/Brewfile ]; then
    echo "  ✗ Error: Brewfile not found: brew/Brewfile"
    exit 1
  fi
  echo "Installing packages from brew/Brewfile..."
  dotbash_run brew bundle --file="$ROOT"/brew/Brewfile
  echo "  ✓ Packages installed successfully"
fi

# Init private Mackup store submodule
echo "Init private Mackup store submodule..."
if [ "$DRY_RUN" = true ]; then
  echo "[dry-run] Init private Mackup store submodule"
else
  set +e
  git submodule update --init --recursive mackup/store
  status=$?
  set -e
  if [ $status -eq 0 ]; then
    echo "  ✓ Init private Mackup store submodule completed"
  else
    echo "  ⚠ Init private Mackup store submodule skipped (optional)"
  fi
fi

# Set Fish as default shell
echo "Set Fish as default shell..."
if [ "$DRY_RUN" = true ]; then
  echo "[dry-run] Set Fish as default shell"
else
  FP=$(command -v fish)
  grep -Fxq "$FP" /etc/shells || echo "$FP" | sudo tee -a /etc/shells
  [ "$SHELL" = "$FP" ] || chsh -s "$FP" "$USER"
  echo "  ✓ Set Fish as default shell completed"
fi

# Install Fish Plugins
echo "Install Fish Plugins..."
if [ "$DRY_RUN" = true ]; then
  echo "[dry-run] Install Fish Plugins"
else
  fish -c "fisher update"
  echo "  ✓ Install Fish Plugins completed"
fi

# Generate Fish completions
echo "Generate Fish completions..."
if [ "$DRY_RUN" = true ]; then
  echo "[dry-run] Generate Fish completions"
else
  set +e
  COMPDIR="$HOME/.config/fish/completions"
  mkdir -p "$COMPDIR"

  emit() {
    local bin="$1" dest="$2"
    shift 2
    if command -v "$bin" >/dev/null 2>&1; then
      "$@" >"$dest" || rm -f "$dest"
    fi
  }

  emit docker "$COMPDIR/docker.fish" docker completion fish
  emit kubectl "$COMPDIR/kubectl.fish" kubectl completion fish
  emit gh "$COMPDIR/gh.fish" gh completion -s fish
  emit supabase "$COMPDIR/supabase.fish" supabase completion fish
  emit orbctl "$COMPDIR/orbctl.fish" orbctl completion fish

  if command -v bun >/dev/null 2>&1; then
    bun completions "$COMPDIR" >/dev/null 2>&1 || true
  fi
  status=$?
  set -e
  if [ $status -eq 0 ]; then
    echo "  ✓ Generate Fish completions completed"
  else
    echo "  ⚠ Generate Fish completions skipped (optional)"
  fi
fi

echo "All shell commands completed successfully!"

