# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
gui:
  nerdFontsVersion: '3'
  showNumstatInFilesView: true
  showRandomTip: false
  showCommandLog: false
git:
  parseEmoji: true
  log:
    showGraph: 'always'
  paging:
    colorArg: always
    pager: delta --paging=never
os:
  openLink: open "$(echo {{link}} | sed 's/%2F/\//g')"
  editPreset: 'nvim'
services:
  'gitlab.booking.com': 'gitlab:gitlab.booking.com' # Work-related
