# Keybindings
## Set Prefix to C-Space
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

## Set keys for splitting
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

## Keep CWD when opening new window
unbind c
bind c new-window -c "#{pane_current_path}"

## Set window shortcuts
bind -n M-1 selectw -t 1
bind -n M-2 selectw -t 2
bind -n M-3 selectw -t 3
bind -n M-4 selectw -t 4
bind -n M-5 selectw -t 5
bind -n M-6 selectw -t 6
bind -n M-7 selectw -t 7
bind -n M-8 selectw -t 8
bind -n M-9 selectw -t 9
bind -n M-c new-window -c '#{pane_current_path}'
bind -n M-p previous-window
bind -n M-n next-window

## Reload config file (change file location to your the tmux.conf you want to use)
bind-key r source-file ~/.tmux.conf \; # display-message "~/.tmux.conf reloaded"

## Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

## Switch panes with prefix
bind -r h select-pane -L  # move left
bind -r j select-pane -D  # move down
bind -r k select-pane -U  # move up
bind -r l select-pane -R  # move right
bind > swap-pane -D       # swap current pane with the next one
bind < swap-pane -U       # swap current pane with the previous one

## Maximize current pane
bind + run "cut -c3- '#{TMUX_CONF}' | sh -s _maximize_pane '#{session_name}' '#D'"

## Pane resizing
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

## LazyGit
bind-key g display-popup -w "80%" -h "80%" -d "#{pane_current_path}" -E "lazygit"

# Options
## Faster Command Sequences
set -s escape-time 10

## Allow multiple commands to be entered without pressing the prefix-key again
set -sg repeat-time 600

## Focus events
set -s focus-events on

## Default Shell
set -g default-shell /opt/homebrew/bin/fish

## Increase Scrollback
set -g history-limit 5000

## Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Enable UTF-8 Support
set -gq status-utf8 on

## Refresh Status line more often
set -g status-interval 1

## Activity
set -g monitor-activity on
set -g visual-activity off

## Fix Tmux colors
# see https://github.com/tmux/tmux/issues/696
# see https://stackoverflow.com/a/41786092
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "screen.xterm-256color"

## Don't rename windows automatically
set -g allow-rename off

## Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

## Renumber windows once closed
set -g renumber-windows on

# Theme
source ~/.dotfiles/tmux/theme/tokyo-night-status.conf

# Plugins
set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'MunifTanjim/tmux-mode-indicator'

# Set plugin directory
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.dotfiles/tmux/plugins/'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.dotfiles/tmux/plugins/tpm/tpm'
