[fish-ai]
configuration = self-hosted

[self-hosted]
provider = self-hosted
server = https://opencode.ai/zen/v1
model = kimi-k2
; api_key = ; API Key is stored locally on device, use fish_ai_put_api_key, don't store in plain text
